### ISSUE TITLE
PIC Decompression

### ISSUE THREAD

**Issue by hansbonini** [Fluvian/mnsg#1]
I was trying to decompress PIC0000 format... did you have success on reproduce the algorithm?

**Comment by Fluvian** [comment]
Sorry for the late reply! I didn't get a notification about this. 

Actually, yes! I have written a very very horribly programmed application, which was mostly the result of the frustration I had with trying to reverse the algorithm, I have not written a cleaner version yet. So far it can only decompress the PIC textures.

I tried cleaning it up a bit and put it up on gist, please tell me if there are any problems: https://gist.github.com/Fluvian/5be437c90e3bffe005daab2e02be7035

**Comment by Fluvian** [comment]
Is there any other games this is used in? I only know that this game, Goemon's Great Adventure and International Track & Field 2000 use it.

**Comment by hansbonini** [comment]
I made some checks on offsets based on your header info and the modes used are 4,8,15 and 16 bpp. Compression looks like Rare ZLIB.

**Comment by Fluvian** [comment]
Interesting! Conversion between BGRA and RGBA happens in-game so that's why I did it there.
