### ISSUE TITLE
"decompress.py" under "tools" doesn't work properly

### ISSUE THREAD

**Issue by LiquidCat64** [Fluvian/mnsg#2]
I don't really have a better way to contact you about this, so apologies if this is not the *best* Github issue in the world.

So, I tested the decompress.py script on two games: Mystical Ninja Starring Goemon and Castlevania 64 (which also uses a Nisitenma-Ichigo table with LZKN64-compressed files exactly like MNSG). I ran it like such for both games and while it created an output ROM, it had no bytes of data in it when opened with Notepad++ and the script's process never finished until I closed the CMD window myself:
![Screenshot_2023-03-04_221627](https://user-images.githubusercontent.com/74896918/223228625-3fde2113-00db-4c17-b578-d95fbd8e3dfe.png)
This is true for both of the mentioned games.

I then tried opening the script in PyCharm just to take a look at it and I noticed that, on lines 75 and 282, there were two functions both named "decompress" in the exact same scope:
![Screenshot 2023-03-06 140529](https://user-images.githubusercontent.com/74896918/223230922-8b71475c-ea83-4fc3-a950-02ccbed3ee42.png)
![Screenshot 2023-03-06 140605](https://user-images.githubusercontent.com/74896918/223230936-0e378738-dd0d-485f-9155-668a796eaef1.png)
The function call on line 258 calls the "decompress" function on line 282 when, in actuality, it appeared to be intended for the line 75 one. So, I renamed the line 75 "decompress" to "decompress_files", updated the function call on line 258 with the same name, ran it again for both games, and *now* it generates a working, decompressed ROM of MNSG.

Sadly, because Konami did not set up handling for decompressed files in CV64's Nisitenma-Ichigo table due to *every last one* of its files being compressed, its decompressed ROM does not boot properly with just this script alone (though it *does* decompress its files and update its NI table properly) and more effort will be required to make that one work. But this script was made with MNSG in mind and it appears to work properly for MNSG after making this small change, so I just thought I'd let you know that you should probably fix this.

**Comment by Fluvian** [comment]
Sorry for the delayed response, I don't really get notifications from issues being created for some reason.

I was made aware of this issue by someone else and have it fixed locally though I didn't bother to update the repo yet. Thanks for the reminder.
